name: Publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'
        required: true
      branch:
        description: 'Branch'
        default: 'master'
        required: true

jobs:
  publish:
    name: Publish
    uses: redis-field-engineering/redis-github-workflows/.github/workflows/publish-maven.yml@main
    with:
      branch: ${{ github.event.inputs.branch }}
      version: ${{ github.event.inputs.version }}
    secrets:
      github-token: ${{ secrets.GIT_ACCESS_TOKEN }}